### ISSUE TITLE
cv2.VideoCapture() not working with this package as I am trying to process my video using lambda function with opencv python.. If you have any solution kindly help me with that, it will be really helpful :)

### ISSUE THREAD

**Issue by harshal2802** [aeddi/aws-lambda-python-opencv#2]

**Comment by aeddi** [comment]
Hello,
can you give me the code you're trying to run along with the error messages returned by Python ?

**Comment by harshal2802** [comment]
When using like this

ret, img = cv2.VideoCapture()

value of ret is coming False every time
Here I am trying to read video as mentioned on Opencv tutorial on official
website using lambda function.

**Comment by aeddi** [comment]
It's maybe not the cause of your problem but `cv2.VideoCapture()` seems to return only one value which is not a boolean but an object.
So according to the official documentation, your code should look like this:

``` python
cap = cv2.VideoCapture('video.avi')
if cap.isOpened():
      #Do some stuff
```

According to the doc. again, VideoCapture needs extra dependencies (ffmpeg/gstreamer) that may not be installed on Lambda.
So you could possibly have to include some binary (e.g dynamic libs) in the archive and find a way to link them properly with OpenCV.
