### ISSUE TITLE
Python 3.6 support?

### ISSUE THREAD

**Issue by wobeng** [aeddi/aws-lambda-python-opencv#4]
Hi,
Aws release lambda runtime python 3.6. Do you have instruction on how to build opencv for python 3?

**Comment by p0wdrdotcom** [comment]
The tough bit about this one is that the Amazon Linux does not have python installed by default.

This process works with the assumption that the system that your code runs on in lambda is similar to the default amazon linux instance.

You would probably have to install python 3 and its library and also build numpy with python3.

**Comment by aeddi** [comment]
@p0wdrdotcom is right again ;)

**Comment by wobeng** [comment]
I built it...do you still need it?

**Comment by aeddi** [comment]
No thanks.

**Comment by charlie0077** [comment]
@wobeng I need opencv in python3.6, can you mind sharing how did you build it?
Thanks.

**Comment by wobeng** [comment]
@charlie0077  what's your email

**Comment by wobeng** [comment]
I sent it to charlie.chen.v@gmail.com

**Comment by chen116** [comment]
Hi @wobeng ,

 can you also show me how you build the opencv with python3.6, thank you very very much!  my email is yvictorck@gmail.com thanks!

**Comment by jontang** [comment]
HI @wobeng , 
wondering if you could also share with me how you built opencv with python3.6.  my email is jontang@gmail.com thanks!
